theme: jekyll-theme-cayman
title: FindMyTeam
description: Find the team you want that will work best for you. We want to help each student get the best experiences out of their group and collaborative experiences.
